# Generated by Django 5.1.7 on 2025-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_payment_method_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='Chưa cung cấp', max_length=20),
        ),
    ]
